open Lang.Il

type ir_var = {
  iv_id  : string;
  iv_typ : typ;
}

type qc_command =
  | QcProp of {
      free_vars     : ir_var list;
        (* User-declared params only. These are generated by il_gen. *)
      all_var_names : id' list;
        (* free_vars names + names bound by premises, in evaluation order.
           Passed to run_prems so their values are available in the env. *)
      goal  : prem;
      prems : prem list;
    }
  | QcGen of {
      free_vars     : ir_var list;
      all_var_names : id' list;
      prems         : prem list;
    }

type t = qc_command list
