(lang dune 3.7)
(cram enable)
(using menhir 2.0)
(using mdx 0.2)
(name spectec)

(generate_opam_files true)

(package
  (name spectec)
  (version 0.0.1)
  (synopsis "SpecTec-Core: A spec mechanization framework")
  (maintainers "kunjeong99@naver.com")
  (depends
    bignum
    core
    core_unix))
